### PR TITLE
Recipies list

### PR DESCRIPTION
**Pull request by AlexRS90**
For this PR:
- Created recipes controller, views and model.
- Coded feature to add a new recipe and delete as well.
- Added a basic style.

### CODE REVIEW

**Review by codepantha — CHANGES_REQUESTED** [review]
Hi @AlexRS90 👋, 

Amazing work so far 👏. I appreciate the hard work you have put into this project but there are some changes you'd need to make before merging.



## Suggested changes ♻️ 

- [ ] If I submit an empty recipe, it stores it in the database. This is not great for our data. Please add model validation to the `recipes` model 🙏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by AlexRS90** [comment]
Hey @codepantherr, sorry for the issue I'll fix it

**Review by codepantha — APPROVED** [review]
Hi @AlexRS90 👋, 

Thank you for implementing the requested changes. Your project is now ready to be merged 🎉 



Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by AlexRS90** [comment]
Great, thanks for your suggestions!!

**Pull request merged**
